version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      DATABASE_PORT: "${POSTGRES_PORT}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main_network
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "${PORT}:${PORT}"
    environment:
      ASYNC_DATABASE_URL: "${ASYNC_DATABASE_URL}"
      SYNC_DATABASE_URL: "${SYNC_DATABASE_URL}"
    depends_on:
        - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - main_network
    env_file:
      - .env
    volumes:
      - .:/app

networks:
  main_network:

volumes:
    postgres-data: